name: Verify Tag with Shorthand

on:
  workflow_dispatch:
    inputs:
      verify:
        description: 'Repository and tag to verify (owner/repo@tag)'
        required: true
        type: string

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Verify Tag
        id: verify
        uses: actionutils/trusted-tag-verifier@v1
        with:
          verify: ${{ github.event.inputs.verify }}
      
      - name: Display Verification Results
        run: |
          echo "Verification Results:"
          echo "===================="
          echo "Verified: ${{ steps.verify.outputs.verified }}"
          echo "Repository: ${{ steps.verify.outputs.repository }}"
          echo "Tag: ${{ steps.verify.outputs.tag-name }}"
          echo "Commit: ${{ steps.verify.outputs.commit-sha }}"
          echo "Tagger: ${{ steps.verify.outputs.tagger-name }} <${{ steps.verify.outputs.tagger-email }}>"
          echo "Message: ${{ steps.verify.outputs.tag-message }}"
          
          echo "===================="
          echo "Certificate Information:"
          echo '${{ steps.verify.outputs.verification-result }}' | jq -r '.certificate_info' | head -n 20
          
          echo "===================="
          echo "Verification Status:"
          echo '${{ steps.verify.outputs.verification-result }}' | jq '.verification'