name: Test Trusted Tag Verifier

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test-verify-tag:
    name: Test Tag Verification
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify Tag (Shorthand)
        id: verify-shorthand
        uses: ./
        with:
          verify: 'actionutils/trusted-tag-releaser@v0.0.30'

      - name: Display Verification Results (Shorthand)
        run: |
          echo "Verified: ${{ steps.verify-shorthand.outputs.verified }}"
          echo "Repository: ${{ steps.verify-shorthand.outputs.repository }}"
          echo "Tag: ${{ steps.verify-shorthand.outputs.tag-name }}"
          echo "Commit: ${{ steps.verify-shorthand.outputs.commit-sha }}"
          echo "Tagger: ${{ steps.verify-shorthand.outputs.tagger-name }} <${{ steps.verify-shorthand.outputs.tagger-email }}>"
          echo "Message: ${{ steps.verify-shorthand.outputs.tag-message }}"

          # Display the full JSON
          echo "Verification Result (JSON):"
          echo '${{ steps.verify-shorthand.outputs.verification-result }}' | jq

      - name: Verify Tag (Explicit Parameters)
        id: verify-explicit
        uses: ./
        with:
          repository: 'actionutils/trusted-tag-releaser'
          tag: 'v0.0.30'
          fail-on-verification-error: 'false'

      - name: Display Verification Results (Explicit Parameters)
        run: |
          echo "Verified: ${{ steps.verify-explicit.outputs.verified }}"
          echo "Repository: ${{ steps.verify-explicit.outputs.repository }}"
          echo "Tag: ${{ steps.verify-explicit.outputs.tag-name }}"
          echo "Commit: ${{ steps.verify-explicit.outputs.commit-sha }}"
          echo "Tagger: ${{ steps.verify-explicit.outputs.tagger-name }} <${{ steps.verify-explicit.outputs.tagger-email }}>"
          echo "Message: ${{ steps.verify-explicit.outputs.tag-message }}"

          # Display the full JSON
          echo "Verification Result (JSON):"
          echo '${{ steps.verify-explicit.outputs.verification-result }}' | jq

      - name: Test Invalid Tag (Should Fail)
        id: verify-invalid-tag
        uses: ./
        with:
          verify: 'actionutils/trusted-tag-releaser@non-existent-tag'
          fail-on-verification-error: 'false'
        continue-on-error: true

      - name: Check Invalid Tag Result
        run: |
          if [[ "${{ steps.verify-invalid-tag.outcome }}" == "failure" ]]; then
            echo "✅ Test passed: Invalid tag verification failed as expected"
          else
            echo "❌ Test failed: Invalid tag verification did not fail"
            exit 1
          fi

      - name: Test Invalid Certificate Issuer (Should Not Fail)
        id: verify-invalid-issuer
        uses: ./
        with:
          repository: 'actionutils/trusted-tag-releaser'
          tag: 'v0.0.30'
          certificate-oidc-issuer: 'https://invalid-issuer.example.com'
          fail-on-verification-error: 'false'

      - name: Check Invalid Certificate Issuer Result
        run: |
          if [[ "${{ steps.verify-invalid-issuer.outputs.verified }}" == "false" ]]; then
            echo "✅ Test passed: Invalid certificate issuer verification returned false as expected"
            echo "Verification Result (JSON):"
            echo '${{ steps.verify-invalid-issuer.outputs.verification-result }}' | jq
          else
            echo "❌ Test failed: Invalid certificate issuer verification did not return false"
            exit 1
          fi

      - name: Test Invalid Certificate Issuer (Should Fail)
        id: verify-invalid-issuer-fail
        uses: ./
        with:
          repository: 'actionutils/trusted-tag-releaser'
          tag: 'v0.0.30'
          certificate-oidc-issuer: 'https://invalid-issuer.example.com'
          fail-on-verification-error: 'true'
        continue-on-error: true

      - name: Check Invalid Certificate Issuer Fail Result
        run: |
          if [[ "${{ steps.verify-invalid-issuer-fail.outcome }}" == "failure" ]]; then
            echo "✅ Test passed: Invalid certificate issuer verification failed as expected"
          else
            echo "❌ Test failed: Invalid certificate issuer verification did not fail"
            exit 1
          fi

  test-downloaded-action:
    name: Test Downloaded Action Path Detection
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      # Now test with empty tag - it should detect the downloaded action
      - name: Test with empty tag (should use downloaded action)
        uses: ./
        with:
          repository: 'actionutils/trusted-tag-verifier'

      - name: Use trusted-tag-verifier as a target
        uses: actionutils/trusted-tag-verifier@v0
        with:
          verify: 'actionutils/trusted-tag-releaser@v0'
